"""document metadata

Revision ID: 55953798339d
Revises: 
Create Date: 2026-06-07 10:45:11.700718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55953798339d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('documents', 'uploaded_by',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'uploaded_by',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.create_table('messages',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('session_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('role', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('content', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['session_id'], ['chat_sessions.id'], name=op.f('messages_session_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
                    )
    op.create_table('chat_sessions',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('chat_sessions_pkey'))
                    )
    # ### end Alembic commands ###
